# Generated by Django 4.2.2 on 2023-07-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_public'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='public',
            new_name='pub',
        ),
    ]
