# Generated by Django 4.2.2 on 2023-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_public_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='panchayath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath_id', models.CharField(max_length=10)),
                ('panchayath_name', models.CharField(max_length=255)),
                ('panchayath_address', models.CharField(max_length=255)),
                ('panchayath_district', models.CharField(max_length=255)),
                ('panchayath_city', models.CharField(max_length=255)),
                ('panchayath_pincode', models.CharField(max_length=255)),
                ('panchayath_contact', models.CharField(max_length=10)),
                ('panchayath_email', models.CharField(max_length=255)),
                ('panchayath_password', models.CharField(max_length=255)),
            ],
        ),
    ]
