# Generated by Django 4.2.2 on 2023-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_panchayath'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsmemberid', models.CharField(max_length=10)),
                ('adsname', models.CharField(max_length=255)),
                ('adsgender', models.CharField(max_length=10)),
                ('adsadharno', models.CharField(max_length=15)),
                ('adspanchayath', models.CharField(max_length=255)),
                ('adsward', models.CharField(max_length=255)),
                ('adscontact', models.CharField(max_length=10)),
                ('adsemail', models.CharField(max_length=255)),
                ('adspassword', models.CharField(max_length=255)),
            ],
        ),
    ]
