# Generated by Django 4.2.2 on 2023-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='workemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emname', models.CharField(max_length=255)),
                ('emaddress', models.CharField(max_length=255)),
                ('empincode', models.CharField(max_length=255)),
                ('emdistrict', models.CharField(max_length=150)),
                ('empanchayath', models.CharField(max_length=255)),
                ('emward', models.CharField(max_length=255)),
                ('emratiocard', models.CharField(max_length=255)),
                ('emadhar', models.CharField(max_length=255)),
                ('emcontact', models.CharField(max_length=15)),
                ('emusername', models.CharField(max_length=150)),
                ('empassword', models.CharField(max_length=150)),
            ],
        ),
    ]
