# Generated by Django 4.2.2 on 2023-07-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_workemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='workrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('panchayath', models.CharField(max_length=255)),
                ('wardno', models.CharField(max_length=255)),
                ('rationcardno', models.CharField(max_length=100)),
                ('taxno', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
