# Generated by Django 4.2.2 on 2023-07-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notifition'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifition',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
