# Generated by Django 4.2.2 on 2023-07-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_notifition_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='workentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdetails', models.TextField(max_length=255)),
                ('startingdate', models.DateField(null=True)),
                ('no_of_days', models.TextField(max_length=255)),
            ],
        ),
    ]
