# Generated by Django 4.2.2 on 2023-07-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_workentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='no_of_days',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='workdetails',
            field=models.CharField(max_length=255),
        ),
    ]
