# Generated by Django 4.2.2 on 2023-07-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_workentry_no_of_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdetails', models.CharField(max_length=255)),
                ('startingdate', models.DateField(null=True)),
                ('no_of_days', models.CharField(max_length=255)),
                ('panchayathid', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='workentry',
        ),
    ]
