# Generated by Django 4.2.2 on 2023-07-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_entry12_delete_workentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='workcomplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workentryid', models.CharField(max_length=255)),
                ('completeworkdetails', models.CharField(max_length=255)),
                ('currentdetails', models.CharField(max_length=255)),
                ('todate', models.DateField(null=True)),
            ],
        ),
    ]
