# Generated by Django 4.2.2 on 2023-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='todate',
            field=models.DateField(null=True),
        ),
    ]
