# Generated by Django 4.2.2 on 2023-07-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyid', models.CharField(max_length=255)),
                ('reply', models.CharField(max_length=255)),
                ('redate', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='replies',
        ),
    ]
