# Generated by Django 4.2.2 on 2023-07-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
