# Generated by Django 4.2.2 on 2023-07-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='empattendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField(null=True)),
                ('attendence', models.CharField(choices=[('P', 'present'), ('A', 'absent')], max_length=25)),
                ('current_date', models.DateField(null=True)),
            ],
        ),
    ]
