# Generated by Django 4.2.2 on 2023-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_empattendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='usertype',
            field=models.CharField(default='ads', max_length=255),
        ),
        migrations.AddField(
            model_name='panchayath',
            name='usertype',
            field=models.CharField(default='panchayath', max_length=255),
        ),
        migrations.AddField(
            model_name='pub',
            name='usertype',
            field=models.CharField(default='public', max_length=255),
        ),
        migrations.AddField(
            model_name='workemployee',
            name='usertype',
            field=models.CharField(default='employee', max_length=255),
        ),
    ]
