# Generated by Django 4.2.2 on 2023-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_ads_usertype_panchayath_usertype_pub_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empattendence',
            name='attendence',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1),
        ),
    ]
