# Generated by Django 4.2.2 on 2023-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_empattendence_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='newwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=15)),
                ('adharno', models.IntegerField(null=True)),
                ('contactno', models.CharField(max_length=255)),
                ('empid', models.CharField(max_length=255)),
            ],
        ),
    ]
