# Generated by Django 4.2.2 on 2023-08-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_newwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=255)),
                ('currentdate', models.DateField(null=True)),
                ('employeeid', models.CharField(max_length=25)),
            ],
        ),
    ]
