# Generated by Django 4.2.2 on 2023-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='workassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workrequestid', models.TextField(max_length=100)),
                ('adsid', models.TextField(max_length=100)),
                ('currentdate', models.DateField(null=True)),
            ],
        ),
    ]
