# Generated by Django 4.2.2 on 2023-08-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_workassign'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cardholder', models.CharField(max_length=100)),
                ('card_number', models.IntegerField(null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('card_expiry_month', models.PositiveIntegerField()),
                ('card_expiry_year', models.PositiveIntegerField()),
                ('amount', models.IntegerField(null=True)),
                ('current_date', models.DateField(null=True)),
                ('worker_id', models.CharField(max_length=100)),
            ],
        ),
    ]
