# Generated by Django 4.2.2 on 2023-08-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='card_expiry_month',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='card_expiry_year',
        ),
        migrations.AddField(
            model_name='salary',
            name='card_expiry',
            field=models.CharField(default='timezone.now', max_length=25),
            preserve_default=False,
        ),
    ]
