# Generated by Django 4.2.2 on 2023-08-08 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_salary_card_expiry_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='card_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='cvv',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
