# Generated by Django 4.2.2 on 2023-08-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_message1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workemployee',
            old_name='emaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='emadhar',
            new_name='adhar_no',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='emcontact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='emdistrict',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='emname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='empanchayath',
            new_name='panchayath',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='empassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='empincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='emratiocard',
            new_name='ratiocard_no',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='emusername',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='workemployee',
            old_name='emward',
            new_name='ward',
        ),
    ]
