# Generated by Django 4.2.2 on 2023-09-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_address_workemployee_emaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message1',
            name='reciever_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ads'),
        ),
        migrations.AlterField(
            model_name='message1',
            name='sender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.workemployee'),
        ),
    ]
