# Generated by Django 4.2.2 on 2023-09-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_ads_adsgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=255)),
                ('current_date', models.DateField(null=True)),
                ('reciever_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.workemployee')),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ads')),
            ],
        ),
    ]
