# Generated by Django 4.2.2 on 2023-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_reply12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='adsemail',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ads',
            name='adsgender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newwork',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='panchayath',
            name='panchayath_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pub',
            name='emailid',
            field=models.EmailField(max_length=255),
        ),
    ]
