# Generated by Django 4.2.2 on 2023-09-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_ads_adsemail_alter_ads_adsgender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayath',
            name='panchayath_id',
        ),
    ]
