# Generated by Django 4.2.2 on 2023-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_panchayath_panchayath_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='land_tax_receipt',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
