# Generated by Django 4.2.2 on 2023-09-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='adsmemberid',
        ),
    ]
