# Generated by Django 4.2.2 on 2023-09-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_ads_adsmemberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifition',
            name='user',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
