# Generated by Django 4.2.2 on 2023-09-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_notifition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='emailid',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
