# Generated by Django 4.2.2 on 2023-09-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_ads_adsemail_alter_panchayath_panchayath_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='emailid',
            field=models.EmailField(error_messages={'unique': 'This email address is already in use.'}, max_length=255, unique=True),
        ),
    ]
