# Generated by Django 4.2.2 on 2023-09-17 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_workemployee_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='public_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
    ]
