# Generated by Django 4.2.2 on 2023-09-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_workrequest_public_id_alter_salary_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrequest',
            name='public_id',
        ),
    ]
