# Generated by Django 4.2.2 on 2023-09-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_workrequest_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
