# Generated by Django 4.2.2 on 2023-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_complaints_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='employeeid',
            field=models.CharField(max_length=15),
        ),
    ]
