# Generated by Django 4.2.2 on 2023-09-18 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_remove_newwork_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newwork',
            name='empid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
