# Generated by Django 4.2.2 on 2023-09-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_newwork_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwork',
            name='empid',
            field=models.IntegerField(null=True),
        ),
    ]
