# Generated by Django 4.2.6 on 2023-10-10 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_newwork_district_newwork_panchayath'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pub',
            name='panchayath',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
